/**
 * Worker API client.
 *
 * Auth is a session cookie set by the Worker, so every request sends
 * credentials. The browser stays on one origin in both environments, which is
 * what keeps that cookie first-party: in development Vite proxies /api to
 * wrangler dev, and in production the same Worker serves both this bundle and
 * the API. So VITE_API_URL is set in no build today and BASE is the empty
 * string, making every path below same-origin and CORS irrelevant to the app's
 * own requests. It stays available for pointing a local front end at a
 * deployed Worker; that origin then has to appear in ALLOWED_ORIGINS.
 */

import { formatMoney } from './lib/format';

const BASE = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '');

export class ApiError extends Error {
  constructor(public status: number, message: string, public code?: string) {
    super(message);
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    credentials: 'include',
    headers: {
      // A FormData body has to set its own content-type: the boundary is
      // generated by the browser and a hand-written header loses it.
      ...(init.body && !(init.body instanceof FormData)
        ? { 'content-type': 'application/json' } : {}),
      ...init.headers,
    },
  });

  if (res.status === 204) return undefined as T;

  let body: any = null;
  try { body = await res.json(); } catch { /* empty or non-JSON */ }

  if (!res.ok) {
    throw new ApiError(res.status, body?.error ?? `Request failed (${res.status})`, body?.code);
  }
  return body as T;
}

const get = <T>(p: string) => request<T>(p);
const post = <T>(p: string, body?: unknown) =>
  request<T>(p, { method: 'POST', body: body === undefined ? undefined : JSON.stringify(body) });
const patch = <T>(p: string, body: unknown) =>
  request<T>(p, { method: 'PATCH', body: JSON.stringify(body) });
const put = <T>(p: string, body: unknown) =>
  request<T>(p, { method: 'PUT', body: JSON.stringify(body) });
const del = <T>(p: string) => request<T>(p, { method: 'DELETE' });

// ---------------------------------------------------------------------------
// Types mirrored from the Worker
// ---------------------------------------------------------------------------
export interface Operator {
  id: string; email: string; business_name: string; trade: string | null;
  timezone: string; country: string; currency: string; language: string;
  location_mode: 'mobile' | 'premises' | 'hybrid';
  fill_model: 'clients' | 'leads' | 'both';
  sms_mode: 'device' | 'twilio';
  min_gap_seconds: number; max_detour_seconds: number; buffer_seconds: number;
  offers_per_wave: number; discount_percent: number; plan: string;
  tagline: string | null; bio: string | null; years_experience: number | null;
  profile_slug: string | null; is_published: number; avatar_key: string | null;
  /** Off by default. Only the operator's own action turns this on. */
  share_location: number;
}

export interface Gap {
  id: string; starts_at: number; ends_at: number;
  is_mobile: number; status: string;
  /** 1 = the whole working day is unbooked, not a hole between jobs. */
  fills_whole_day: number;
  created_by_cancellation_of: string | null;
  live_offers: number; label: string; duration_minutes: number;
}

export interface MapArea {
  name: string; slug: string; lat: number; lng: number;
  trades: string[];
  slot_count: number;
  from_price: string | null;
  next_when: string | null;
}

/** The one review a card has room for. */
export interface ReviewSnippet {
  body: string;
  /** Already cut to "Debra D." by the server — never a full surname. */
  author: string;
  rating: number;
}

export interface PublicSlot {
  gap_id: string; operator_id: string; business_name: string;
  trade: string | null; profile_slug: string | null;
  service_id: string | null; service_name: string;
  starts_at: number; ends_at: number; duration_seconds: number;
  price_cents: number; deposit_cents: number; currency: string;
  when: string; price: string;
  detour_minutes: number | null; proximity: string | null;
  anchor_lat: number | null; anchor_lng: number | null;
  area_slug: string;
  /** A sample listing seeded so the map is not blank, not a real business. */
  is_sample: boolean;

  /**
   * Null means nobody has reviewed this business, which is not the same as a
   * bad score. A card must render the absence as an absence — no stars, no
   * "0.0", no "New!" badge that implies a rating we do not have.
   */
  rating: number | null;
  review_count: number;
  /** "Hired 314 times." Jobs that actually completed. */
  hired_count: number;
  /** Switched on and working right now, not merely free later this week. */
  online: boolean;
  /**
   * A background check was run on this person. It records that a check
   * happened — it is not this platform vouching for the result, and it is not
   * a trade licence, so it must not be worded as either.
   */
  background_check: boolean;
  years_in_business: number | null;
  employees: number | null;
  /** The newest review with words in it. Null when there are none. */
  review_snippet: ReviewSnippet | null;

  /**
   * The operator's own headshot or logo. Run it through `photoUrl`.
   *
   * Null for most businesses, and null has to render as an absence — initials,
   * or nothing — never as a stock face, which would be a photograph of a
   * person who does not work there.
   */
  avatar_key: string | null;
  /**
   * One photograph from the operator's portfolio, for the card thumbnail. Also
   * `photoUrl`.
   *
   * From work_photos and from nowhere else. The other pictures this product
   * holds are the evidence photographs taken during a job — the inside of a
   * customer's house — and those are published only by the customer who took
   * them, onto their own review, one at a time. None of them will ever arrive
   * in this field, and nothing on a card may go looking for them.
   */
  work_photo_key: string | null;
}

export interface Candidate {
  kind: 'client' | 'lead';
  client_id: string; lead_id: string | null; service_id: string | null;
  first_name: string; phone_e164: string | null; language: string | null;
  duration_seconds: number; price_cents: number; title: string;
  overdue_days: number | null; urgency: number | null;
  drive_in_seconds: number | null; drive_out_seconds: number | null;
  detour_seconds: number | null; score: number; reasons: string[];
}

export interface CreatedOffer {
  offer_id: string; client_id: string; first_name: string;
  phone_e164: string | null; url: string; message: string;
  send: { ios: string; android: string; body: string };
  rank: number; score: number; reasons: string[];
}

export interface Appointment {
  id: string; client_id: string | null; service_id: string | null;
  starts_at: number; ends_at: number; status: string;
  address_line: string | null; price_cents: number | null; source: string;
  first_name: string | null; last_name: string | null; service_name: string | null;
}

export interface Client {
  id: string; first_name: string; last_name: string | null;
  phone_e164: string | null; email: string | null;
  address_line: string | null; postcode: string | null;
  geocode_status: string; default_service_id: string | null;
  last_serviced_at: number | null; next_due_at: number | null;
  visit_count: number; no_show_count: number;
  sms_consent: number; opted_out_at: number | null; language: string | null;
}

export interface Lead {
  id: string; client_id: string; title: string; description: string | null;
  quoted_price_cents: number | null; estimated_duration_seconds: number | null;
  parts_required: number; parts_ready: number; urgency: number; status: string;
  first_name: string; last_name: string | null; phone_e164: string | null;
}

export interface Service {
  id: string; name: string; duration_seconds: number; price_cents: number;
  cadence_days: number | null; is_active: number;
}

export interface WorkingHour {
  id: string; weekday: number; start_minute: number; end_minute: number;
}

export interface ServiceArea {
  id: string; name: string; slug: string;
  lat: number; lng: number; radius_meters: number;
}

export interface WorkPhoto {
  id: string; r2_key: string; caption: string | null;
  width: number | null; height: number | null;
  content_type: string; sort_order: number;
}

export interface PublicOperator {
  business_name: string; tagline: string | null; bio: string | null;
  years_experience: number | null; trade: string | null;
  avatar_key: string | null; country: string;
  is_sample?: boolean;
}

/** Photos are served by the Worker from R2, on this same origin. */
export const photoUrl = (key: string) => `/api/public/photo/${encodeURIComponent(key)}`;

export interface Notification {
  id: string; kind: string; title: string; body: string | null;
  appointment_id: string | null; starts_at: number | null;
  read_at: number | null; created_at: number;
}

export interface Thread {
  id: string; operator_id: string; gap_id: string | null; appointment_id: string | null;
  guest_name: string; subject: string | null; last_message_at: number;
  operator_unread: number; guest_unread: number; status: 'open' | 'closed';
  created_at: number;
  /** Guest view only — a signed-out customer has no operator record to read. */
  business_name?: string; profile_slug?: string | null;
  timezone?: string; locale?: string;
  booking?: {
    service_name: string; starts_at: number; ends_at: number;
    price: string; address_line: string | null;
    /** Null for the older single-slot claims that predate orders. */
    order_item_id: string | null;
  } | null;
}

export interface ChatMessage {
  id: string; thread_id: string; sender: 'guest' | 'operator';
  body: string; created_at: number;
  /** 1 when a contact detail was stripped before this was stored. */
  redacted?: number;
  /**
   * Only ever present on the response to your OWN send, and never stored. The
   * other side is not told "they tried to give you a phone number" -- that is
   * an accusation a regex cannot support, and it would poison a conversation
   * over somebody signing off with their number out of habit.
   */
  notice?: string | null;
}

export interface Watch {
  id: string; postcode: string; lat: number; lng: number; country: string;
  trades: string[] | null; max_detour_seconds: number;
  max_price_cents: number | null; label: string | null; active: number;
  email: string | null; email_verified_at: number | null; email_failed_count: number;
  last_notified_at: number | null; notify_count: number;
  created_at: number; updated_at: number;
}

export type TrackView =
  | { visible: false; reason: string }
  | {
      visible: true; lat: number; lng: number;
      eta_seconds: number; distance_meters: number; recorded_at: number;
      dest_lat: number; dest_lng: number;
    };

export interface VanPosition {
  operator_id: string; lat: number; lng: number;
  accuracy_meters: number | null; heading: number | null; speed_mps: number | null;
  recorded_at: number; updated_at: number;
}

export interface Opening {
  id: string; operator_id: string; starts_at: number; ends_at: number;
  duration_seconds: number; is_mobile: number; status: string;
  source: 'detected' | 'posted'; service_ids: string[];
  created_at: number; updated_at: number;
}

export interface PricedService {
  service_id: string; name: string;
  duration_seconds: number; price_cents: number; price: string;
  parts_policy: PartsPolicy;
  parts_note: string | null;
  parts_estimate_low_cents: number | null;
  parts_estimate_high_cents: number | null;
  /**
   * The one sentence about parts, written once on the server so the slot page,
   * the basket, the confirmation and the receipt cannot drift into four
   * different answers to "will my bill go up". Null when there is nothing to
   * say, which is the common case.
   */
  parts_line: string | null;
}

export interface PricedItem {
  gap_id: string; operator_id: string; business_name: string; currency: string;
  starts_at: number; ends_at: number; gap_ends_at: number; when: string;
  services: PricedService[];
  duration_seconds: number; price_cents: number; price: string;
  fits: boolean; problems: Array<{ code: string; message: string }>;
}

export interface PricedOrder {
  items: PricedItem[]; currency: string; duration_seconds: number;
  total_cents: number; total: string;
  ok: boolean; problems: Array<{ code: string; message: string }>;
}

export interface TradeRule {
  license: 'required' | 'over_threshold' | 'none';
  authority?: string; authority_name?: string; why: string;
}

export interface Credentials {
  license_kind: string | null; license_number: string | null;
  license_state: string | null; license_expires_at: number | null;
  unlicensed_ack: number;
  insurer: string | null; policy_number: string | null;
  insurance_expires_at: number | null; insured_ack: number;
}

export interface GapServices {
  gap_id: string; operator_id: string; business_name: string;
  trade: string | null; profile_slug: string | null; is_sample: boolean;
  is_mobile: number; starts_at: number; ends_at: number;
  window_seconds: number; currency: string; when: string;
  /**
   * Shaped as PricedService so the menu the customer ticks from and the
   * priced basket are the same thing. They were separate shapes and the parts
   * fields had to be added to both; one of the two would eventually have been
   * missed, and the one that gets missed is always the one the customer reads
   * before deciding.
   */
  services: PricedService[];
}

export interface Country {
  iso2: string; name: string; dial: string; currency: string;
  default_timezone: string; multi_timezone: boolean; has_postal_codes: boolean;
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Parts
// ---------------------------------------------------------------------------
export type PartsPolicy = 'none' | 'included' | 'quoted';

export interface PartsQuote {
  id: string;
  order_item_id: string;
  operator_id: string;
  thread_id: string | null;
  description: string;
  parts_cents: number;
  labor_cents: number;
  total_cents: number;
  currency: string;
  status: 'sent' | 'approved' | 'declined' | 'withdrawn' | 'expired';
  expires_at: number | null;
  decided_at: number | null;
  charged_at: number | null;
  created_at: number;
  updated_at: number;
}

/** One booked job an operator can raise a quote against. */
export interface QuotableBooking {
  id: string;
  appointment_id: string | null;
  starts_at: number;
  ends_at: number;
  price_cents: number;
  parts_cents: number;
  currency: string;
  guest_name: string | null;
  services: string | null;
  live_quotes: number;
  thread_id: string | null;
  /** When the operator tapped "I'm here". Null until they do. */
  arrived_at: number | null;
  /** When the customer's code was entered. The real start of the job. */
  code_verified_at: number | null;
  cancelled_at: number | null;
}

export interface LeadFee {
  id: string;
  order_item_id: string;
  cents: number;
  currency: string;
  reason: 'cancelled_on_arrival' | 'cancelled_same_day' | 'no_show';
  status: 'owed' | 'paid' | 'waived';
  note: string | null;
  settled_at: number | null;
  created_at: number;
}

export interface RatingSummary {
  average: number | null;
  count: number;
  distribution: Record<1 | 2 | 3 | 4 | 5, number>;
  /** "Exceptional", "Very good"… A bare 4.9 invites arithmetic nobody wanted. */
  label: string | null;
}

export interface Review {
  id: string;
  rating: number;
  /** Already cut to "Debra D." by the server. */
  author_name: string;
  body: string | null;
  /** Exactly what that customer booked, copied at the time. */
  details: string | null;
  reply: string | null;
  replied_at: number | null;
  created_at: number;
  /** Photo ids this customer chose to publish. Never the whole job. */
  photos?: string[];
}

export interface ProfileFaq { id: string; question: string; answer: string; position: number }

/** One thing this business does, priced. Its working notes are not in here. */
export interface PublicService {
  id: string;
  name: string;
  duration_seconds: number;
  price_cents: number;
}

/**
 * One band of the working week, in minutes from midnight in the operator's own
 * timezone — 540 is 09:00. Render them through `operator.timezone` and not the
 * reader's clock: a business open until 18:00 in Los Angeles is not open until
 * 02:00, which is what the browser would make of these numbers.
 *
 * A weekday can have several bands (a lunch break is two), and a weekday that
 * appears in no band is a day this business does not work. An operator who has
 * never set hours has none at all, so an empty array means "they have not
 * said" and must not be drawn as a week of closed days.
 */
export interface PublicHours {
  /** 0 = Sunday. */
  weekday: number;
  start_minute: number;
  end_minute: number;
}

/** Everything the profile page shows, in the shape the reference arranged it. */
export interface PublicProfileResponse {
  operator: PublicOperator & {
    work_location: 'i_travel' | 'they_travel' | 'both';
    employees: number;
    years_in_business: number | null;
    payment_methods: string | null;
    social_instagram: string | null;
    social_facebook: string | null;
    social_tiktok: string | null;
    background_check_name: string | null;
    background_checked_at: number | null;
    background_check_provider: string | null;
    hired_count: number;
    /** IANA name. The only thing that makes working_hours readable. */
    timezone: string;
  };
  photos: WorkPhoto[];
  rating: RatingSummary;
  reviews: Review[];
  mentions: Array<{ word: string; n: number }>;
  faqs: ProfileFaq[];
  areas: string[];
  /**
   * Everything this business sells — not only the services that happen to be
   * attached to an open gap right now, which is the subset the listing side
   * can see and which changes hour to hour.
   */
  services: PublicService[];
  /** When they work. Empty when they have never set any. */
  working_hours: PublicHours[];
}

export interface OnlineStatus {
  online: boolean;
  until: number | null;
  since: number | null;
  seconds_left: number;
  radius_meters: number;
}

/** A job offered to somebody who is switched on. Five minutes to answer it. */
export interface PendingRequest {
  id: string;
  guest_name: string;
  service_name: string | null;
  starts_at: number;
  duration_seconds: number;
  price_cents: number;
  currency: string;
  address_line: string | null;
  note: string | null;
  seconds_left: number;
}

export interface Estimate {
  id: string;
  thread_id: string;
  request: string;
  description: string | null;
  price_cents: number | null;
  duration_seconds: number | null;
  starts_at: number | null;
  currency: string | null;
  status: 'asked' | 'quoted' | 'accepted' | 'declined' | 'withdrawn' | 'expired';
  created_at: number;
}

export interface Trade { slug: string; label: string; hint?: string }
export interface TradeCategory { key: string; label: string; trades: Trade[] }

export interface Vehicle {
  make: string | null; model: string | null;
  color: string | null; plate: string | null;
}

/** The customer's copy of the code, and the van to look for. */
export interface JobCode {
  order_item_id: string;
  /** Null once the operator has entered it — a used code is not shown. */
  code: string | null;
  verified_at: number | null;
  starts_at: number;
  vehicle: Vehicle;
  vehicle_label: string | null;
}

export type Stage = 'before' | 'during' | 'after';

export interface JobPhoto {
  id: string;
  order_item_id: string;
  uploaded_by: 'operator' | 'customer';
  stage: Stage;
  content_type: string | null;
  width: number | null;
  height: number | null;
  caption: string | null;
  created_at: number;
}

export interface ProofSummary {
  before: JobPhoto[]; during: JobPhoto[]; after: JobPhoto[]; total: number;
}

/** The "did they do the work anyway?" prompt, when one is waiting. */
export interface PendingQuestion {
  order_item_id: string;
  services: string | null;
  business_name: string;
  refund: string;
  refund_cents: number;
  hold_until: number | null;
}

export interface RefundDecision {
  /**
   * 'most' is three quarters back, 'some' is a quarter. They replaced a single
   * 'half' when the cliff at twelve hours became the graduated ladder, and
   * this union still named the rung that no longer exists.
   */
  reason: 'full' | 'grace' | 'most' | 'some' | 'none' | 'operator_cancelled';
  /** 25, 75 or 100. */
  percent: number;
  cents: number;
  /** Written on the server so the warning and the outcome cannot drift apart. */
  message: string;
}

export interface Standing {
  kind: 'operator' | 'customer';
  id: string;
  no_show_strikes: number;
  suspended_until: number | null;
  banned_at: number | null;
  blocked: boolean;
  message: string | null;
}

export interface CardOnFile {
  payment_brand: string | null;
  payment_last4: string | null;
  payment_added_at: number | null;
}

export interface FeesResponse {
  owed: { cents: number; currency: string | null; count: number; amount: string };
  fees: LeadFee[];
  /** The sentence to show the operator when listings are blocked. Null when clear. */
  blocked: string | null;
}

/**
 * What came back from erasing a customer.
 *
 * `removed` is keyed by database table — the Worker's own vocabulary, not a
 * customer's — so nothing renders it. `standing_retained` is the field a
 * person has to be told about, because it names the one thing an erasure
 * deliberately leaves behind.
 */
export interface ErasureResult {
  removed: Record<string, number>;
  standing_retained: boolean;
}

export const api = {
  // --- parts ---------------------------------------------------------------
  quotableBookings: () => get<{ bookings: QuotableBooking[] }>('/api/parts/bookings'),
  partsQuotes: (orderItemId?: string) =>
    get<{ quotes: PartsQuote[] }>(
      `/api/parts/quotes${orderItemId ? `?order_item_id=${encodeURIComponent(orderItemId)}` : ''}`),
  sendPartsQuote: (b: {
    order_item_id: string; description: string; parts_cents: number; labor_cents?: number;
  }) => post<{ quote: PartsQuote }>('/api/parts/quotes', b),
  withdrawPartsQuote: (id: string) => del<{ ok: true }>(`/api/parts/quotes/${id}`),

  guestParts: (token: string) =>
    get<{ quotes: PartsQuote[]; parts_cents: number }>(
      `/api/public/threads/${encodeURIComponent(token)}/parts`),
  decidePartsQuote: (token: string, id: string, decision: 'approved' | 'declined') =>
    post<{ quote: PartsQuote }>(
      `/api/public/threads/${encodeURIComponent(token)}/parts/${id}`, { decision }),

  // --- arrival, cancellation, fees -----------------------------------------
  markArrived: (orderItemId: string) =>
    post<{ arrived_at: number }>(`/api/bookings/${orderItemId}/arrived`),
  cancelBooking: (orderItemId: string, reason?: string) =>
    post<{ order_item_id: string; fee: LeadFee | null; relisted: boolean }>(
      `/api/bookings/${orderItemId}/cancel`, { reason }),
  refundQuote: (token: string, orderItemId: string) =>
    get<{ refund: RefundDecision }>(
      `/api/public/threads/${encodeURIComponent(token)}/refund/${orderItemId}`),
  guestCancel: (token: string, orderItemId: string, reason?: string) =>
    post<{ order_item_id: string; fee: null; relisted: boolean }>(
      `/api/public/threads/${encodeURIComponent(token)}/cancel/${orderItemId}`, { reason }),
  fees: () => get<FeesResponse>('/api/fees'),

  // --- proof of the job ----------------------------------------------------
  // FormData bodies go through request() untouched: the browser sets its own
  // content-type with the multipart boundary, and a hand-written header
  // loses it.
  jobProof: (orderItemId: string) =>
    get<ProofSummary>(`/api/bookings/${orderItemId}/proof`),
  addJobProof: (orderItemId: string, form: FormData) =>
    request<{ photo: JobPhoto }>(`/api/bookings/${orderItemId}/proof`,
      { method: 'POST', body: form }),
  guestProof: (token: string, orderItemId: string) =>
    get<ProofSummary>(
      `/api/public/threads/${encodeURIComponent(token)}/proof/${orderItemId}`),
  guestAddProof: (token: string, orderItemId: string, form: FormData) =>
    request<{ photo: JobPhoto }>(
      `/api/public/threads/${encodeURIComponent(token)}/proof/${orderItemId}`,
      { method: 'POST', body: form }),

  // --- the start code and the van ------------------------------------------
  // The catalogue, grouped. Served by the Worker so the browser never holds a
  // second copy that can drift out of step with it.
  tradeCatalog: () => get<{ categories: TradeCategory[] }>('/api/trade-catalog'),
  publicTradeCatalog: () =>
    get<{ categories: TradeCategory[] }>('/api/public/trade-catalog'),

  // --- open for work right now ---------------------------------------------
  onlineStatus: () => get<OnlineStatus>('/api/online'),
  goOnline: (radiusMeters?: number) =>
    post<OnlineStatus>('/api/online', { radius_meters: radiusMeters }),
  goOffline: () => del<OnlineStatus>('/api/online'),
  pendingRequests: () => get<{ requests: PendingRequest[] }>('/api/online/requests'),
  acceptRequest: (id: string) =>
    post<{ ok: true }>(`/api/online/requests/${id}/accept`),
  declineRequest: (id: string) =>
    post<{ ok: true }>(`/api/online/requests/${id}/decline`),
  onlineNear: (lat: number, lng: number, trade?: string) =>
    get<{ operators: Array<Record<string, unknown>> }>(
      `/api/public/online?lat=${lat}&lng=${lng}${trade ? `&trade=${encodeURIComponent(trade)}` : ''}`),

  // --- estimates asked for in the chat --------------------------------------
  askEstimate: (token: string, request: string) =>
    post<{ estimate: Estimate }>(
      `/api/public/threads/${encodeURIComponent(token)}/estimates`, { request }),
  guestEstimates: (token: string) =>
    get<{ estimates: Estimate[] }>(
      `/api/public/threads/${encodeURIComponent(token)}/estimates`),
  decideEstimate: (token: string, id: string, decision: 'accepted' | 'declined') =>
    post<{ estimate: Estimate }>(
      `/api/public/threads/${encodeURIComponent(token)}/estimates/${id}`, { decision }),
  estimates: (status?: string) =>
    get<{ estimates: Estimate[] }>(`/api/estimates${status ? `?status=${status}` : ''}`),
  quoteEstimate: (id: string, b: {
    description: string; price_cents: number; duration_seconds: number; starts_at: number;
  }) => post<{ estimate: Estimate }>(`/api/estimates/${id}/quote`, b),
  withdrawEstimate: (id: string) => del<{ ok: true }>(`/api/estimates/${id}`),

  vehicle: () => get<{ vehicle: Vehicle }>('/api/vehicle'),
  saveVehicle: (v: Partial<Vehicle>) => put<{ vehicle: Vehicle }>('/api/vehicle', v),
  verifyStartCode: (orderItemId: string, code: string) =>
    post<{ verified_at: number }>(`/api/bookings/${orderItemId}/code`, { code }),
  jobCode: (token: string) =>
    get<{ job: JobCode | null }>(`/api/public/threads/${encodeURIComponent(token)}/code`),
  reportVehicle: (token: string, orderItemId: string, note?: string) =>
    post<{ ok: true }>(
      `/api/public/threads/${encodeURIComponent(token)}/vehicle/${orderItemId}`, { note }),

  // --- two-sided arrival, and the one question -----------------------------
  confirmArrival: (token: string, orderItemId: string) =>
    post<{ arrival_confirmed_at: number }>(
      `/api/public/threads/${encodeURIComponent(token)}/arrived/${orderItemId}`),
  pendingQuestion: (token: string) =>
    get<{ question: PendingQuestion | null }>(
      `/api/public/threads/${encodeURIComponent(token)}/pending`),
  answerWork: (token: string, orderItemId: string, answer: 'done' | 'not_done') =>
    post<{ settlement: string; refund_cents: number }>(
      `/api/public/threads/${encodeURIComponent(token)}/answer/${orderItemId}`, { answer }),

  // --- card on file, standing, no-shows ------------------------------------
  // No card number ever passes through here. The processor's own form takes
  // the details and hands back a reference; that reference is all this sends.
  paymentMethod: () => get<{ card: CardOnFile | null }>('/api/payment-method'),
  savePaymentMethod: (b: { ref: string; brand?: string; last4?: string }) =>
    post<{ ok: true }>('/api/payment-method', b),

  // --- getting rid of things -----------------------------------------------
  // Neither of these is reversible and neither has a grace period, so both
  // call sites put a confirmation in front of them. See DeleteMyData.tsx and
  // CloseAccount.tsx.
  eraseMyData: (token: string) =>
    del<ErasureResult>(`/api/public/threads/${encodeURIComponent(token)}/data`),
  /**
   * The Worker clears the session cookie on its own success response, so the
   * caller's only remaining job is to drop the local copy of the operator.
   */
  closeAccount: () => post<{ removed: Record<string, number> }>('/api/account/close'),

  standing: () => get<{ standing: Standing; has_card: boolean; blocked: string | null }>(
    '/api/standing'),
  reportNoShow: (orderItemId: string, note?: string) =>
    post<{ id: string }>(`/api/bookings/${orderItemId}/no-show`, { note }),
  guestReportNoShow: (token: string, orderItemId: string, note?: string) =>
    post<{ id: string }>(
      `/api/public/threads/${encodeURIComponent(token)}/no-show/${orderItemId}`, { note }),

  countries: () => get<{ countries: Country[] }>('/api/countries'),

  requestSignIn: (body: { email: string; business_name?: string; country?: string; timezone?: string }) =>
    post<{ ok: true; sign_in_link?: string }>('/api/auth/request', body),
  verify: (token: string) => post<{ ok: true }>('/api/auth/verify', { token }),
  publicMap: (postcode?: string) =>
    get<{
      areas: MapArea[]; slots: PublicSlot[];
      located: { postcode: string; place: string | null } | null;
    }>(`/api/public/map${postcode ? `?postcode=${encodeURIComponent(postcode)}` : ''}`),

  guestThread: (token: string) =>
    get<{ thread: Thread; messages: ChatMessage[] }>(
      `/api/public/threads/${encodeURIComponent(token)}`),
  guestSend: (token: string, body: string) =>
    post<{ message: ChatMessage }>(
      `/api/public/threads/${encodeURIComponent(token)}/messages`, { body }),
  startGuestThread: (b: {
    operator_id: string; gap_id?: string; guest_name: string;
    subject?: string; first_message?: string;
    /** See placeOrder below for what this is and when it is left out. */
    turnstile_token?: string;
  }) => post<{ thread: Thread; token: string; link: string }>('/api/public/threads', b),

  threads: (unreadOnly?: boolean) =>
    get<{ threads: Thread[]; unread: number }>(`/api/threads${unreadOnly ? '?unread=1' : ''}`),
  thread: (id: string) => get<{ thread: Thread; messages: ChatMessage[] }>(`/api/threads/${id}`),
  threadSend: (id: string, body: string) =>
    post<{ message: ChatMessage }>(`/api/threads/${id}/messages`, { body }),
  markThreadRead: (id: string) => post<{ ok: true }>(`/api/threads/${id}/read`, {}),

  postOpening: (b: { starts_at: number; ends_at: number; service_ids?: string[] }) =>
    post<{ opening: Opening }>('/api/openings', b),
  openings: (from: number, to: number) =>
    get<{ openings: Opening[] }>(`/api/openings?from=${from}&to=${to}`),
  cancelOpening: (id: string) => del<{ ok: true }>(`/api/openings/${id}`),

  gapServices: (gapId: string) =>
    get<GapServices>(`/api/public/gaps/${encodeURIComponent(gapId)}/services`),
  priceOrder: (items: Array<{ gap_id: string; service_ids: string[] }>) =>
    post<PricedOrder>('/api/public/orders/price', { items }),
  placeOrder: (b: {
    items: Array<{ gap_id: string; service_ids: string[] }>;
    guest_name: string; phone: string; email?: string;
    address_line?: string; postcode?: string; thread_token?: string;
    /**
     * A solved Turnstile challenge, when there was one to solve.
     *
     * Optional because the widget is off in every build until
     * VITE_TURNSTILE_SITE_KEY is set, and because a widget that failed to load
     * must not stop somebody booking. The Worker is the one that decides
     * whether its absence matters — it answers 400 `turnstile_missing` when it
     * does, and Book.tsx turns that into a sentence.
     */
    turnstile_token?: string;
  }) => post<{
    order_id: string; status: string; currency: string;
    total_cents: number; total: string;
    thread_token: string; link: string;
  }>('/api/public/orders', b),

  credentials: () =>
    get<{ credentials: Credentials; rule: TradeRule; blockers: string[] }>('/api/credentials'),
  saveCredentials: (b: Partial<Credentials>) =>
    patch<{ credentials: Credentials; blockers: string[] }>('/api/credentials', b),

  vapidKey: () => get<{ key: string | null }>('/api/public/vapid-key'),
  trades: () => get<{ trades: string[] }>('/api/public/trades'),
  createWatch: (b: {
    postcode: string; trades?: string[] | null; max_detour_seconds?: number;
    max_price_cents?: number | null; label?: string; email?: string;
    /**
     * See placeOrder. Creating a watch is challenged; editing, pausing and
     * deleting one are not, because those need the token in the link and only
     * the person who created it has that.
     */
    turnstile_token?: string;
  }) => post<{ watch: Watch; token: string; link: string }>('/api/public/watches', b),
  watch: (token: string) =>
    get<{ watch: Watch }>(`/api/public/watches/${encodeURIComponent(token)}`),
  updateWatch: (token: string, body: Partial<{
    postcode: string; trades: string[] | null; max_detour_seconds: number;
    max_price_cents: number | null; label: string; active: boolean; email: string;
  }>) => patch<{ watch: Watch }>(`/api/public/watches/${encodeURIComponent(token)}`, body),
  deleteWatch: (token: string) =>
    del<{ ok: true }>(`/api/public/watches/${encodeURIComponent(token)}`),
  addPushSubscription: (token: string, sub: PushSubscriptionJSON) =>
    post<{ ok: true }>(`/api/public/watches/${encodeURIComponent(token)}/subscriptions`, sub),
  removePushSubscription: (token: string, endpoint: string) =>
    request<{ ok: true }>(`/api/public/watches/${encodeURIComponent(token)}/subscriptions`,
      { method: 'DELETE', body: JSON.stringify({ endpoint }) }),

  trackCustomer: (token: string) =>
    get<TrackView>(`/api/public/threads/${encodeURIComponent(token)}/track`),
  trackMe: () => get<{ position: VanPosition | null; trail: Array<{ lat: number; lng: number; recorded_at: number }> }>('/api/track/me'),
  trackPing: (b: Record<string, unknown>) =>
    post<{ stored: boolean; reason?: string }>('/api/track/ping', b),
  shareLocation: (on: boolean) =>
    post<{ ok: true }>('/api/track/share', { share_location: on }),

  notifications: (unreadOnly?: boolean) =>
    get<{ notifications: Notification[]; unread: number }>(
      `/api/notifications${unreadOnly ? '?unread=1' : ''}`),
  markNotificationsRead: (ids?: string[]) =>
    post<{ ok: true }>('/api/notifications/read', ids ? { ids } : {}),

  serviceAreas: () => get<{ areas: ServiceArea[] }>('/api/service-areas'),
  createServiceArea: (body: { name: string; postcode: string; radius_km?: number }) =>
    post<{ area: ServiceArea }>('/api/service-areas', body),
  deleteServiceArea: (id: string) => del<{ ok: true }>(`/api/service-areas/${id}`),

  profile: () => get<{ operator: Operator; photos: WorkPhoto[] }>('/api/profile'),
  // Named `body`, not `patch`: a parameter called patch shadows the helper.
  saveProfile: (body: { tagline?: string; bio?: string; years_experience?: number }) =>
    patch<{ operator: Operator }>('/api/profile', body),
  publishProfile: () => post<{ slug: string }>('/api/profile/publish', {}),
  unpublishProfile: () => post<{ ok: true }>('/api/profile/unpublish', {}),
  uploadPhoto: (file: File, caption?: string) => {
    const form = new FormData();
    form.append('file', file);
    if (caption) form.append('caption', caption);
    return request<{ photo: WorkPhoto }>('/api/profile/photos', { method: 'POST', body: form });
  },
  deletePhoto: (id: string) => del<{ ok: true }>(`/api/profile/photos/${id}`),
  reorderPhotos: (ids: string[]) =>
    post<{ photos: WorkPhoto[] }>('/api/profile/photos/order', { ids }),
  publicProfile: (slug: string) =>
    get<PublicProfileResponse>(`/api/public/profile/${slug}`),
  publicReviews: (operatorId: string, sort?: string) =>
    get<{ rating: RatingSummary; reviews: Review[] }>(
      `/api/public/reviews/${operatorId}${sort ? `?sort=${sort}` : ''}`),
  reviewableBookings: (token: string) =>
    get<{ bookings: Array<{ order_item_id: string; ends_at: number; services: string | null }> }>(
      `/api/public/threads/${encodeURIComponent(token)}/reviewable`),
  leaveReview: (token: string, b: { order_item_id: string; rating: number; body?: string }) =>
    post<{ review: Review }>(
      `/api/public/threads/${encodeURIComponent(token)}/review`, b),
  releaseReviewPhoto: (token: string, photoId: string, isPublic: boolean) =>
    post<{ ok: true }>(
      `/api/public/threads/${encodeURIComponent(token)}/review-photo/${photoId}`,
      { public: isPublic }),
  replyToReview: (id: string, text: string) =>
    post<{ ok: true }>(`/api/reviews/${id}/reply`, { text }),

  faqs: () => get<{ faqs: ProfileFaq[] }>('/api/faqs'),
  saveFaq: (b: { id?: string; question: string; answer: string; position?: number }) =>
    put<{ id: string }>('/api/faqs', b),
  deleteFaq: (id: string) => del<{ ok: true }>(`/api/faqs/${id}`),
  startDemo: () => post<{ ok: true }>('/api/auth/demo'),
  logout: () => post<{ ok: true }>('/api/auth/logout'),
  me: () => get<{ operator: Operator; is_demo?: boolean }>('/api/me'),
  deleteService: (id: string) => del<{ ok: true }>(`/api/services/${id}`),
  updateSettings: (body: Partial<Operator>) => patch<{ operator: Operator }>('/api/settings', body),

  gaps: (from?: number, to?: number) => {
    const q = new URLSearchParams();
    if (from) q.set('from', String(from));
    if (to) q.set('to', String(to));
    return get<{ gaps: Gap[] }>(`/api/gaps${q.toString() ? `?${q}` : ''}`);
  },
  detectGaps: (days = 14) => post<{ ok: true; created: number }>('/api/gaps/detect', { days }),
  candidates: (gapId: string) =>
    get<{ gap: Gap; candidates: Candidate[] }>(`/api/gaps/${gapId}/candidates`),
  sendOffers: (gapId: string, candidates?: Array<Pick<Candidate, 'kind' | 'client_id' | 'lead_id'>>) =>
    post<{ offers: CreatedOffer[]; sms_mode: string; reason?: string }>(
      `/api/gaps/${gapId}/offers`, candidates ? { candidates } : {}),
  dismissGap: (gapId: string) => post<{ ok: true }>(`/api/gaps/${gapId}/dismiss`, {}),

  appointments: (from: number, to: number) =>
    get<{ appointments: Appointment[] }>(`/api/appointments?from=${from}&to=${to}`),
  createAppointment: (body: Record<string, unknown>) =>
    post<{ id: string }>('/api/appointments', body),
  updateAppointment: (id: string, body: Record<string, unknown>) =>
    patch<{ ok: true; next_due_at: number | null }>(`/api/appointments/${id}`, body),
  cancelAppointment: (id: string, cancelled_by: 'client' | 'operator' = 'client') =>
    post<{ ok: true; gaps: Gap[] }>(`/api/appointments/${id}/cancel`, { cancelled_by }),

  clients: (opts: { q?: string; overdue?: boolean } = {}) => {
    const p = new URLSearchParams();
    if (opts.q) p.set('q', opts.q);
    if (opts.overdue) p.set('overdue', '1');
    return get<{ clients: Client[] }>(`/api/clients${p.toString() ? `?${p}` : ''}`);
  },
  createClient: (body: Record<string, unknown>) => post<{ id: string }>('/api/clients', body),
  updateClient: (id: string, body: Record<string, unknown>) =>
    patch<{ ok: true }>(`/api/clients/${id}`, body),

  leads: (status = 'open') => get<{ leads: Lead[] }>(`/api/leads?status=${status}`),
  createLead: (body: Record<string, unknown>) => post<{ id: string }>('/api/leads', body),
  updateLead: (id: string, body: Record<string, unknown>) =>
    patch<{ ok: true }>(`/api/leads/${id}`, body),

  services: () => get<{ services: Service[] }>('/api/services'),
  createService: (body: Record<string, unknown>) => post<{ id: string }>('/api/services', body),

  workingHours: () => get<{ working_hours: WorkingHour[] }>('/api/working-hours'),
  setWorkingHours: (working_hours: Array<{ weekday: number; start_minute: number; end_minute: number }>) =>
    put<{ ok: true }>('/api/working-hours', { working_hours }),
};

// ---------------------------------------------------------------------------
// Formatting — always driven by the operator's own country and language.
// ---------------------------------------------------------------------------
export const localeFor = (op: Pick<Operator, 'country' | 'language'> | null) =>
  op ? `${op.language || 'en'}-${op.country}` : 'en-US';

export function money(cents: number, op: Operator | null): string {
  if (!op) return String(cents / 100);
  const zeroDecimal = ['JPY', 'KRW', 'CLP', 'ISK', 'VND'].includes(op.currency);
  try {
    return new Intl.NumberFormat(localeFor(op), {
      style: 'currency', currency: op.currency,
      minimumFractionDigits: zeroDecimal ? 0 : 2,
      maximumFractionDigits: zeroDecimal ? 0 : 2,
    }).format(zeroDecimal ? cents : cents / 100);
  } catch {
    return `${(cents / 100).toFixed(2)} ${op.currency}`;
  }
}

export function timeRange(startS: number, endS: number, op: Operator | null): string {
  const tz = op?.timezone ?? 'UTC';
  const loc = localeFor(op);
  const day = new Intl.DateTimeFormat(loc, {
    timeZone: tz, weekday: 'short', day: 'numeric', month: 'short',
  }).format(new Date(startS * 1000));
  const t = (s: number) => new Intl.DateTimeFormat(loc, {
    timeZone: tz, hour: '2-digit', minute: '2-digit', hourCycle: 'h23',
  }).format(new Date(s * 1000));
  return `${day}, ${t(startS)}–${t(endS)}`;
}

export function clockTime(s: number, op: Operator | null): string {
  return new Intl.DateTimeFormat(localeFor(op), {
    timeZone: op?.timezone ?? 'UTC', hour: '2-digit', minute: '2-digit', hourCycle: 'h23',
  }).format(new Date(s * 1000));
}

export function shortDate(s: number, op: Operator | null): string {
  return new Intl.DateTimeFormat(localeFor(op), {
    timeZone: op?.timezone ?? 'UTC', day: 'numeric', month: 'short',
  }).format(new Date(s * 1000));
}

/**
 * "landscaping and gardening" -> "Landscaping and gardening".
 *
 * Trade slugs are stored lower case, because that is how the operator typed
 * them and how every query matches them, and they are printed in the middle of
 * sentences as often as at the start of one. CSS `text-transform: capitalize`
 * would give "Landscaping And Gardening", which reads as a headline; only the
 * first letter moves and the rest is left exactly as it was entered.
 *
 * Lived as a private copy in six files, two of which carried a comment claiming
 * it rewrote the words as well as the case.
 */
export const sentence = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * "1h 30m" — how long a gap or a booking runs for.
 *
 * Deliberately terser than the "1 hr 30 min" the cost guides and the
 * server-rendered pages spell out. This one is read at a glance off a phone on
 * a dashboard, where the shortest unambiguous form wins; those are read as
 * prose inside a sentence. The two are not drift and should not be unified.
 */
export const durationLabel = (seconds: number): string => {
  const h = Math.floor(seconds / 3600);
  const m = Math.round((seconds % 3600) / 60);
  return h && m ? `${h}h ${m}m` : h ? `${h}h` : `${m}m`;
};

/** How late a client is, in the same words the Worker uses. */
export function lateLabel(days: number | null): string | null {
  if (days === null) return null;
  if (days < 0) return days === -1 ? 'due tomorrow' : `due in ${-days} days`;
  if (days === 0) return 'due today';
  if (days < 14) return `${days} days late`;
  return `${Math.floor(days / 7)} weeks late`;
}
